const products = [
  {
    name: "Product 1",
    description: "Description for Product 1",
    price: 19.99,
    quantity: 50,
    category: "Electronics",
    image: "https://example.com/product1.jpg",
  },
  {
    name: "Product 2",
    description: "Description for Product 2",
    price: 9.99,
    quantity: 100,
    category: "Clothing",
    image: "https://example.com/product2.jpg",
  },
  {
    name: "Product 3",
    description: "Description for Product 3",
    price: 24.99,
    quantity: 75,
    category: "Home & Kitchen",
    image: "https://example.com/product3.jpg",
  },
  {
    name: "Product 4",
    description: "Description for Product 4",
    price: 29.99,
    quantity: 25,
    category: "Sports & Outdoors",
    image: "https://example.com/product4.jpg",
  },
  {
    name: "Product 5",
    description: "Description for Product 5",
    price: 34.99,
    quantity: 10,
    category: "Books",
    image: "https://example.com/product5.jpg",
  },
  {
    name: "Product 6",
    description: "Description for Product 6",
    price: 44.99,
    quantity: 5,
    category: "Beauty & Personal Care",
    image: "https://example.com/product6.jpg",
  },
  {
    name: "Product 7",
    description: "Description for Product 7",
    price: 12.99,
    quantity: 150,
    category: "Toys & Games",
    image: "https://example.com/product7.jpg",
  },
  {
    name: "Product 8",
    description: "Description for Product 8",
    price: 14.99,
    quantity: 125,
    category: "Automotive",
    image: "https://example.com/product8.jpg",
  },
  {
    name: "Product 9",
    description: "Description for Product 9",
    price: 17.99,
    quantity: 75,
    category: "Tools & Home Improvement",
    image: "https://example.com/product9.jpg",
  },
  {
    name: "Product 10",
    description: "Description for Product 10",
    price: 22.99,
    quantity: 50,
    category: "Pet Supplies",
    image: "https://example.com/product10.jpg",
  },
  {
    name: "Product 11",
    description: "Description for Product 11",
    price: 27.99,
    quantity: 25,
    category: "Music & Instruments",
    image: "https://example.com/product11.jpg",
  },
  {
    name: "Product 12",
    description: "Description for Product 12",
    price: 32.99,
    quantity: 10,
    category: "Office Products",
    image: "",
  },
];
